services:
  web:
    image: ghcr.io/esaiaswestberg/klistra_nu:latest
    ports:
      - "${WEB_PORT}:8080"
    environment:
      - DB_PATH=/data/klistra.db
      - GIN_MODE=release
    volumes:
      - klistra-data:/data
    restart: always

volumes:
  klistra-data:
